# This workflow will build a pacman package from namban
name: package namban for pacman
on:
  release:
    types:
      - created

env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }}
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages via Pacman
        run: |
         pacman -Sy
         pacman --noconfirm -S base-devel pango glib2 librsvg unzip zip fakeroot python python-gobject gtk4 github-cli
         useradd -m builder
         passwd -d builder
         echo 'builder ALL=(ALL) NOPASSWD: ALL' | tee /etc/sudoers.d/builder
         chown -R builder:builder $GITHUB_WORKSPACE

      - name: Make Package
        run: |
         cd package/archlinux
         su builder -c "bash build.sh"
      - name: Upload zst file to the release
        run: |
          echo $(ls)
          cd $GITHUB_WORKSPACE/package/archlinux/build
          gh release upload ${{ github.event.release.tag_name }} ./namban*zst -R ${{ github.repository }}
